############################
## Author
############################

author:
  name: gushanskaya
  image: author.png
  greeting: |
    –Ø –Ω–∞—É—á—É —Ç–µ–±—è –æ—Ü–∏—Ñ—Ä–æ–≤—ã–≤–∞—Ç—å —Ç–≤–æ–π –±–∏–∑–Ω–µ—Å
    –ø—Ä–µ–≤—Ä–∞—â–∞—è —Ö–∞–æ—Å –≤ —É–ø—Ä–∞–≤–ª—è–µ–º—É—é —Å–∏—Å—Ç–µ–º—É.
    –ò –º–∞—Å—à—Ç–∞–±–∏—Ä–æ–≤–∞—Ç—å—Å—è, –∫–æ–≥–¥–∞ ¬´–≤—Å–µ —É–∂–µ –≤–Ω–µ–¥—Ä–∏–ª–∏¬ª :tada:
  icon: ":wave:"


############################
## Links
############################

links:
  - website: https://learn.gushanskaya.ru/
    title: "GitHub –†–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π"
  - instagram: https://instagram.com/asya_gushanskaya/
    title: "–ú–æ–π –ò–Ω—Å—Ç–∞–≥—Ä–∞–º"
  - telegram: https://t.me/asyagushanskaya
    title: "–ú–æ–π Telegram"
  - youtube: https://www.youtube.com/@asyagushanskaya
    title: "–ú–æ–π YouTube –ö–∞–Ω–∞–ª"



############################
## Colunms of Links
############################

monochrome: true

# between 2 & 6 columns are supported (both incl)
columns: 2

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: false

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: false

###############################
## OpenGraph & Twitter Cards
###############################

title: asya.gushanskaya.ru
description: "Demo site build with L1nkr & Hugo"
images:
  - thumbnail.png

footer_text: '<a href="https://t.me/ebashordie" target="_blank" rel="noopener noreferrer">Create by üñ§</a>'


